# Based on https://github.com/libpnet/libpnet

name: Install WinPcap Developer Pack
description: Installs the WinPcap Developer Pack
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: powershell
      run: |
        Invoke-WebRequest -UseBasicParsing https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip -OutFile "${Env:TEMP}\wpd.zip"
        Expand-Archive -LiteralPath "${Env:TEMP}\wpd.zip" -DestinationPath "${Env:TEMP}\wpd"
        Get-ChildItem -Path "${Env:TEMP}\wpd\WpdPack\Lib\*" -Recurse | Move-Item -Destination "${Env:LIB}"
