# Based on https://github.com/libpnet/libpnet

name: Install WinPcap Developer Pack
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        Invoke-WebRequest -UseBasicParsing https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip -OutFile "${Env:TEMP}\wpd.zip"
        Expand-Archive -LiteralPath "${Env:TEMP}\wpd.zip" -DestinationPath "${Env:TEMP}\wpd"
        Move-Item -LiteralPath "${Env:TEMP}\wpd\WpdPack\Lib" -Destination lib
